Repository handong-app/CMS, pull requests merged in 2025-06, with the labels that each got.

#81 ✨ Feat : complete program endpoint & test
  .bruno/v1/course/courseCreate.bru
  .bruno/v1/course/courseDelete.bru
  .bruno/v1/course/courseFectchChildren.bru
  .bruno/v1/course/courseList.bru
  .bruno/v1/course/courseUpdate.bru
  .bruno/v1/program/programGet.bru
  .bruno/v1/program/programList.bru
  .bruno/v1/program/programUserProgress.bru
  src/main/java/com/handongapp/cms/config/JacksonConfig.java
  src/main/java/com/handongapp/cms/controller/v1/ProgramController.java
  src/main/java/com/handongapp/cms/mapper/ProgramMapper.java
  src/main/java/com/handongapp/cms/service/ProgramService.java
  src/main/java/com/handongapp/cms/service/impl/ClubServiceImpl.java
  src/main/java/com/handongapp/cms/service/impl/CourseServiceImpl.java
  src/main/java/com/handongapp/cms/service/impl/ProgramServiceImpl.java
  src/main/resources/mapper/ClubMapper.xml
  src/main/resources/mapper/CourseMapper.xml
  src/main/resources/mapper/ProgramMapper.xml
Labels: feat, be

#104 🐛 Bug : Fix club upsertion api
  src/main/java/com/handongapp/cms/dto/v1/ClubDto.java
  src/main/java/com/handongapp/cms/service/impl/ClubServiceImpl.java
Labels: bug, be

#106 Feat/70 s3 node file upload api
  .bruno/v1/club/getClubProfile.bru
  .bruno/v1/course/courseCreate.bru
  .bruno/v1/node/nodeCreate.bru
  .bruno/v1/s3/Get upload presigned url.bru
  .bruno/v1/s3/Node upload complete.bru
  .bruno/v1/s3/Node upload presigned url.bru
  .bruno/v1/s3/Notify upload complete.bru
  build.gradle
  src/main/java/com/handongapp/cms/config/S3Config.java
  src/main/java/com/handongapp/cms/config/SecurityConfig.java
  src/main/java/com/handongapp/cms/controller/v1/S3Controller.java
  src/main/java/com/handongapp/cms/domain/TbFileList.java
  src/main/java/com/handongapp/cms/domain/TbNode.java
  src/main/java/com/handongapp/cms/domain/enums/ClubUserRole.java
  src/main/java/com/handongapp/cms/domain/enums/FileStatus.java
  src/main/java/com/handongapp/cms/domain/enums/VideoStatus.java
  src/main/java/com/handongapp/cms/domain/model/FileMetaData.java
  src/main/java/com/handongapp/cms/domain/model/FileNodeData.java
  src/main/java/com/handongapp/cms/domain/model/QuizNodeData.java
  src/main/java/com/handongapp/cms/domain/model/TextNodeData.java
  src/main/java/com/handongapp/cms/domain/model/VideoMetaData.java
  src/main/java/com/handongapp/cms/domain/model/VideoNodeData.java
  src/main/java/com/handongapp/cms/dto/v1/NodeDto.java
  src/main/java/com/handongapp/cms/dto/v1/S3Dto.java
  src/main/java/com/handongapp/cms/exception/GlobalExceptionHandler.java
  src/main/java/com/handongapp/cms/exception/data/DataUpdateException.java
  src/main/java/com/handongapp/cms/mapper/NodeMapper.java
  src/main/java/com/handongapp/cms/repository/ClubRoleRepository.java
  src/main/java/com/handongapp/cms/repository/FileListRepository.java
  src/main/java/com/handongapp/cms/repository/UserClubRoleRepository.java
  src/main/java/com/handongapp/cms/service/PresignedUrlService.java
  src/main/java/com/handongapp/cms/service/UploadNotifyService.java
  src/main/java/com/handongapp/cms/service/impl/NodeServiceImpl.java
  src/main/java/com/handongapp/cms/service/impl/PresignedUrlServiceImpl.java
  src/main/java/com/handongapp/cms/service/impl/UploadNotifyServiceImpl.java
  src/main/java/com/handongapp/cms/util/FileUtil.java
  src/main/resources/mapper/NodeMapper.xml
Labels: enhancement, feat, be

#114 [BE/HOTFIX] fetch only related comments
  src/main/resources/mapper/NodeGroupMapper.xml
Labels: bug, be

#116 [BE/FEAT] 노드 일반 파일, 이미지 READ
  .bruno/v1/folder.bru
  .bruno/v1/node-group/nodeGroupList.bru
  src/main/java/com/handongapp/cms/service/impl/NodeGroupServiceImpl.java
Labels: enhancement, feat, be

#112 ✨ Feat: api/v1/node-group/next endpoint
  .bruno/v1/node-group/nodeGroupNext.bru
  src/main/java/com/handongapp/cms/controller/v1/NodeGroupController.java
  src/main/java/com/handongapp/cms/dto/v1/NodeGroupDto.java
  src/main/java/com/handongapp/cms/repository/NodeGroupRepository.java
  src/main/java/com/handongapp/cms/repository/SectionRepository.java
  src/main/java/com/handongapp/cms/service/NodeGroupService.java
  src/main/java/com/handongapp/cms/service/impl/NodeGroupServiceImpl.java
Labels: feat, be

#135 [BE/FEAT] DownloadUrlWithOriginalFileName 구현
  src/main/java/com/handongapp/cms/service/PresignedUrlService.java
  src/main/java/com/handongapp/cms/service/impl/NodeGroupServiceImpl.java
  src/main/java/com/handongapp/cms/service/impl/PresignedUrlServiceImpl.java
Labels: enhancement, feat, be

#141 [FE]138/feat course page api
  src/main/front/src/components/coursePage/SectionCourses.tsx
  src/main/front/src/pages/CoursePage.tsx
  src/main/front/src/types/courseData.types.ts
Labels: feat, fe

#134 Feat/127 comment crud api
  .bruno/v1/comment/Delete Comment.bru
  .bruno/v1/comment/create-comment.bru
  .bruno/v1/comment/list-comments.bru
  .bruno/v1/comment/update-comment.bru
  src/main/java/com/handongapp/cms/controller/v1/CommentController.java
  src/main/java/com/handongapp/cms/dto/v1/CommentDto.java
  src/main/java/com/handongapp/cms/mapper/CustomQueryMapper.java
  src/main/java/com/handongapp/cms/repository/CommentRepository.java
  src/main/java/com/handongapp/cms/service/CommentService.java
  src/main/java/com/handongapp/cms/service/impl/CommentServiceImpl.java
  src/main/resources/mapper/ClubMapper.xml
  src/main/resources/mapper/CustomQueryMapper.xml
  src/main/resources/mapper/ProgramMapper.xml
Labels: feat, be

#145 [FE/BE] 동아리 및 프로그램 페이지 API 연결 및 Progress 로직 설정
  .bruno/v1/user/Get Program.bru
  src/main/front/src/components/ClubPage/ClubBadge.tsx
  src/main/front/src/components/course/CourseItem.test.tsx
  src/main/front/src/components/course/CourseItem.tsx
  src/main/front/src/components/course/CourseLeaderboard.test.tsx
  src/main/front/src/components/course/CourseLeaderboard.tsx
  src/main/front/src/components/course/CourseList.tsx
  src/main/front/src/hooks/userData.ts
  src/main/front/src/hooks/userProgram.ts
  src/main/front/src/pages/ClubPage.tsx
  src/main/front/src/pages/CoursePage.tsx
  src/main/front/src/pages/NodeGroupTest.tsx
  src/main/front/src/pages/ProgramPage.tsx
  src/main/front/src/store/programStore.ts
  src/main/front/src/types/process.types.ts
  src/main/front/src/types/program.types.ts
  src/main/front/src/utils/calculateProcess.test.ts
  src/main/front/src/utils/calculateProcess.ts
  src/main/front/src/utils/courseListParser.ts
  src/main/front/src/utils/currentProgram.test.ts
  src/main/front/src/utils/currentProgram.ts
  src/main/front/tsconfig.json
  src/main/front/vite.config.ts
  src/main/java/com/handongapp/cms/controller/v1/UserController.java
  src/main/java/com/handongapp/cms/dto/v1/ProgramDto.java
  src/main/java/com/handongapp/cms/mapper/ProgramMapper.java
  src/main/java/com/handongapp/cms/service/UserService.java
  src/main/java/com/handongapp/cms/service/impl/UserServiceImpl.java
  src/main/resources/mapper/ProgramMapper.xml
Labels: enhancement, feat, fe, be

#151 [BE/FEAT] 댓글 작성자 이름 반환
  src/main/java/com/handongapp/cms/controller/v1/CommentController.java
  src/main/java/com/handongapp/cms/dto/v1/CommentDto.java
  src/main/java/com/handongapp/cms/dto/v1/CommentResponseDto.java
  src/main/java/com/handongapp/cms/repository/CommentRepository.java
  src/main/java/com/handongapp/cms/service/CommentService.java
  src/main/java/com/handongapp/cms/service/impl/CommentServiceImpl.java
Labels: feat, be

#157 Feat/67 admin
  .bruno/v1/course/courseCreate.bru
  .bruno/v1/node-group/Create NodeGroup.bru
  .bruno/v1/node-group/Delete NodeGroup.bru
  .bruno/v1/node-group/Update NodeGroup.bru
  .bruno/v1/node/node Delete.bru
  .bruno/v1/node/nodeCreate.bru
  .bruno/v1/node/nodeUpdate.bru
  .bruno/v1/s3/Node upload presigned url.bru
  .bruno/v1/section/sectionCreate.bru
  .bruno/v1/section/sectionUpdate.bru
  src/main/front/eslint.config.no-any.js
  src/main/front/package-lock.json
  src/main/front/package.json
  src/main/front/src/admin-club/components/AdminClubMemberTable.tsx
  src/main/front/src/admin-club/components/AdminProgramEdit.tsx
  src/main/front/src/admin-club/components/AdminRoot.tsx
  src/main/front/src/admin-club/pages/AdminClubMemberListPage.tsx
  src/main/front/src/admin-club/pages/AdminClubMemberPage.tsx
  src/main/front/src/admin-club/pages/AdminClubSettingPage.tsx
  src/main/front/src/admin-club/pages/AdminCommentListPage.tsx
  src/main/front/src/admin-club/pages/AdminCourseDetailPage/AddSectionButton.tsx
  src/main/front/src/admin-club/pages/AdminCourseDetailPage/AdminCourseDetailPage.tsx
  src/main/front/src/admin-club/pages/AdminCourseDetailPage/EditSectionDialog.tsx
  src/main/front/src/admin-club/pages/AdminCourseDetailPage/SectionList.tsx
  src/main/front/src/admin-club/pages/AdminCourseDetailPage/components/Section.tsx
  src/main/front/src/admin-club/pages/AdminCourseDetailPage/components/SectionCourses.tsx
  src/main/front/src/admin-club/pages/AdminCourseNodeGroup/AdminCourseDetailNodeGroupPage.tsx
  src/main/front/src/admin-club/pages/AdminCourseNodeGroup/FileUploadBox.tsx
  src/main/front/src/admin-club/pages/AdminCourseNodeGroup/NodeFile.tsx
  src/main/front/src/admin-club/pages/AdminCourseNodeGroup/NodeImage.tsx
  src/main/front/src/admin-club/pages/AdminCourseNodeGroup/NodeQuiz.tsx
  src/main/front/src/admin-club/pages/AdminCourseNodeGroup/NodeRenderer.tsx
  src/main/front/src/admin-club/pages/AdminCourseNodeGroup/NodeText.tsx
  src/main/front/src/admin-club/pages/AdminCourseNodeGroup/NodeVideo.tsx
  src/main/front/src/admin-club/pages/AdminCourseNodeGroup/milkdown-overrides.css
  src/main/front/src/admin-club/pages/AdminCoursePage.tsx
  src/main/front/src/admin-club/pages/AdminProgramListPage.tsx
  src/main/front/src/admin-club/pages/AdminProgramPage.tsx
  src/main/front/src/admin-club/pages/AdminTestPage.tsx
  src/main/front/src/admin-club/pages/index.tsx
  src/main/front/src/components/course/CourseItem.tsx
  src/main/front/src/components/course/CourseList.tsx
  src/main/front/src/main.tsx
  src/main/front/src/pages/CoursePage.tsx
  src/main/front/src/tools/tools.tsx
  src/main/front/src/types/clubmember.types.ts
  src/main/front/src/types/node.types.ts
  src/main/java/com/handongapp/cms/controller/v1/CourseController.java
  src/main/java/com/handongapp/cms/controller/v1/NodeController.java
  src/main/java/com/handongapp/cms/controller/v1/NodeGroupController.java
  src/main/java/com/handongapp/cms/controller/v1/S3Controller.java
  src/main/java/com/handongapp/cms/controller/v1/SectionController.java
  src/main/java/com/handongapp/cms/dto/v1/NodeDto.java
  src/main/java/com/handongapp/cms/dto/v1/NodeGroupDto.java
  src/main/java/com/handongapp/cms/dto/v1/SectionDto.java
  src/main/java/com/handongapp/cms/exception/GlobalExceptionHandler.java
  src/main/java/com/handongapp/cms/service/impl/CourseServiceImpl.java
  src/main/java/com/handongapp/cms/service/impl/PresignedUrlServiceImpl.java
  src/main/java/com/handongapp/cms/service/impl/UploadNotifyServiceImpl.java
  src/main/resources/mapper/NodeGroupMapper.xml
Labels: feat, fe, be

#164 [BE/FEAT] 163 banner profile image upload
  .bruno/v1/s3/Club banner upload.bru
  .bruno/v1/s3/Course banner upload.bru
  .bruno/v1/s3/Upload Complete.bru
  .bruno/v1/s3/User profile upload.bru
  src/main/java/com/handongapp/cms/controller/v1/S3Controller.java
  src/main/java/com/handongapp/cms/domain/TbClub.java
  src/main/java/com/handongapp/cms/domain/TbCourse.java
  src/main/java/com/handongapp/cms/domain/TbFileList.java
  src/main/java/com/handongapp/cms/domain/TbUser.java
  src/main/java/com/handongapp/cms/dto/v1/ClubDto.java
  src/main/java/com/handongapp/cms/dto/v1/CourseDto.java
  src/main/java/com/handongapp/cms/dto/v1/UserDto.java
  src/main/java/com/handongapp/cms/repository/impl/CourseRepositoryImpl.java
  src/main/java/com/handongapp/cms/service/ClubService.java
  src/main/java/com/handongapp/cms/service/CourseService.java
  src/main/java/com/handongapp/cms/service/NodeService.java
  src/main/java/com/handongapp/cms/service/PresignedUrlService.java
  src/main/java/com/handongapp/cms/service/UploadNotifyService.java
  src/main/java/com/handongapp/cms/service/UserService.java
  src/main/java/com/handongapp/cms/service/impl/ClubServiceImpl.java
  src/main/java/com/handongapp/cms/service/impl/CourseServiceImpl.java
  src/main/java/com/handongapp/cms/service/impl/NodeServiceImpl.java
  src/main/java/com/handongapp/cms/service/impl/PresignedUrlServiceImpl.java
  src/main/java/com/handongapp/cms/service/impl/UploadNotifyServiceImpl.java
  src/main/java/com/handongapp/cms/service/impl/UserServiceImpl.java
Labels: enhancement, feat, be

#176 Feat/173 additional features
  .bruno/v1/club/Get All Clubs.bru
  .bruno/v1/club/Join Club.bru
  .bruno/v1/program/programJoin.bru
  src/main/java/com/handongapp/cms/controller/v1/ClubController.java
  src/main/java/com/handongapp/cms/controller/v1/ProgramController.java
  src/main/java/com/handongapp/cms/domain/TbProgramParticipant.java
  src/main/java/com/handongapp/cms/dto/v1/ClubDto.java
  src/main/java/com/handongapp/cms/dto/v1/ProgramDto.java
  src/main/java/com/handongapp/cms/repository/ClubRepository.java
  src/main/java/com/handongapp/cms/repository/TbClubRoleRepository.java
  src/main/java/com/handongapp/cms/repository/TbProgramParticipantRepository.java
  src/main/java/com/handongapp/cms/repository/TbProgramRepository.java
  src/main/java/com/handongapp/cms/repository/TbUserClubRoleRepository.java
  src/main/java/com/handongapp/cms/service/ClubService.java
  src/main/java/com/handongapp/cms/service/ProgramService.java
  src/main/java/com/handongapp/cms/service/impl/ClubServiceImpl.java
  src/main/java/com/handongapp/cms/service/impl/ProgramServiceImpl.java
Labels: feat, be

#167 :sparkles:FE/Feat: connect course-nodeGroup page
  src/main/front/src/components/coursePage/SectionCourses.tsx
  src/main/front/src/pages/CoursePage.tsx
Labels: feat, fe

#186 [FE/Feat] node gropu page create data UI
  src/main/front/src/components/NodeGroupPage/DownloadFileBox.tsx
  src/main/front/src/components/NodeGroupPage/ImagePreviewWithDownload.tsx
  src/main/front/src/components/NodeGroupPage/NodeGroupPage.test.tsx
  src/main/front/src/main.tsx
  src/main/front/src/pages/NodeGroupPage.tsx
  src/main/front/src/types/nodeGroupData.types.ts
Labels: feat, fe

#198 Feat/195 add program endpoint
  .bruno/v1/program/AddCourseToProgram.bru
  .bruno/v1/program/CreateProgram.bru
  src/main/java/com/handongapp/cms/controller/v1/ProgramController.java
  src/main/java/com/handongapp/cms/domain/TbProgramCourse.java
  src/main/java/com/handongapp/cms/dto/v1/ProgramDto.java
  src/main/java/com/handongapp/cms/repository/TbProgramCourseRepository.java
  src/main/java/com/handongapp/cms/repository/TbProgramRepository.java
  src/main/java/com/handongapp/cms/service/ProgramService.java
  src/main/java/com/handongapp/cms/service/impl/ProgramServiceImpl.java
Labels: feat, be

#207 FE/FEAT 동아리 목록/관리자 프로그램 관리
  src/main/front/package-lock.json
  src/main/front/package.json
  src/main/front/src/admin-club/components/AdminProgramEdit.tsx
  src/main/front/src/admin-club/components/CourseAddDialog.tsx
  src/main/front/src/admin-club/pages/AdminProgramListPage.tsx
  src/main/front/src/admin-club/pages/AdminProgramPage.tsx
  src/main/front/src/components/ClubThumbnail.tsx
  src/main/front/src/components/ClubThumbnailList.tsx
  src/main/front/src/main.tsx
  src/main/front/src/pages/ClubListPage.tsx
  src/main/front/src/pages/ClubPage.tsx
  src/main/front/src/tools/api.ts
  src/main/front/src/utils/currentProgram.ts
  src/main/front/src/utils/getMostRecentNodeGroupForUser.test.ts
  src/main/front/src/utils/getMostRecentNodeGroupForUser.ts
Labels: feat, fe

#202 🚑️ Hotfix: remove emptyjson error
  src/main/java/com/handongapp/cms/controller/v1/CourseController.java
  src/main/java/com/handongapp/cms/controller/v1/ProgramController.java
Labels: be

#211 [FE] 사소한 수정사항
  src/main/front/src/App.tsx
  src/main/front/src/components/NodeGroupPage/NextButton.tsx
  src/main/front/src/components/common/MyAppBar.tsx
  src/main/front/src/components/course/CourseList.tsx
  src/main/front/src/components/course/CourseProgress.tsx
  src/main/front/src/main.tsx
  src/main/front/src/pages/LandingPage.tsx
  src/main/front/src/pages/NodeGroupPage.tsx
  src/main/front/src/pages/ProfilePage.tsx
  src/main/front/src/pages/ProgramPage.tsx
  src/main/front/src/tools/api.ts
Labels: fe

#215 [FE/Feat] node group page comment
  package-lock.json
  package.json
  src/main/front/src/components/NodeGroupPage/CommentSection.tsx
  src/main/front/src/components/NodeGroupPage/MarkdownViwer.tsx
  src/main/front/src/pages/NodeGroupPage.tsx
  src/main/front/src/utils/usePostComment.ts
Labels: feat, fe

#213 Feat/105 transcode status listener
  src/main/java/com/handongapp/cms/domain/model/VideoMetaData.java
  src/main/java/com/handongapp/cms/dto/v1/S3Dto.java
  src/main/java/com/handongapp/cms/listener/TranscodeStatusListener.java
  src/main/java/com/handongapp/cms/listener/TranscodeStatusMessage.java
  src/main/java/com/handongapp/cms/service/NodeService.java
  src/main/java/com/handongapp/cms/service/impl/NodeServiceImpl.java
  src/main/java/com/handongapp/cms/service/impl/UploadNotifyServiceImpl.java
  src/main/resources/application.yaml
Labels: enhancement, feat, be

#182 [BE/FEAT] 프로그램 진행 상황 JSON 참가자 사진에 Pre-signed URL 삽입
  .bruno/v1/program/programUserProgress.bru
  src/main/java/com/handongapp/cms/repository/ClubRepository.java
  src/main/java/com/handongapp/cms/repository/UserRepository.java
  src/main/java/com/handongapp/cms/service/impl/ProgramServiceImpl.java
Labels: enhancement, feat, be

#224 :bug: fe/fix: update navigation paths to club page in GoogleCallback …
  src/main/front/src/pages/GoogleCallback.tsx
  src/main/front/src/pages/LandingPage.tsx
  src/main/front/src/pages/ProfileRegistrationPage.tsx
Labels: fe
