Repository handong-app/CMS, pull requests merged in 2025-05, with the labels that each got.

#6 Feat/5 login
  build.gradle
  src/main/java/com/handongapp/cms/CmsApplication.java
  src/main/java/com/handongapp/cms/config/CorsFilterConfiguration.java
  src/main/java/com/handongapp/cms/config/SecurityConfig.java
  src/main/java/com/handongapp/cms/controller/GoogleLoginController.java
  src/main/java/com/handongapp/cms/domain/AuditingFields.java
  src/main/java/com/handongapp/cms/domain/Tbuser.java
  src/main/java/com/handongapp/cms/repository/TbuserRepository.java
  src/main/java/com/handongapp/cms/security/AuthService.java
  src/main/java/com/handongapp/cms/security/AuthServiceImpl.java
  src/main/java/com/handongapp/cms/security/JwtAuthorizationFilter.java
  src/main/java/com/handongapp/cms/security/LoginProperties.java
  src/main/java/com/handongapp/cms/security/PrincipalDetails.java
  src/main/java/com/handongapp/cms/security/PrincipalDetailsService.java
  src/main/java/com/handongapp/cms/security/dto/GoogleOAuthResponse.java
  src/main/java/com/handongapp/cms/security/dto/GoogleTokenResponse.java
  src/main/java/com/handongapp/cms/security/dto/GoogleUserInfoResponse.java
  src/main/java/com/handongapp/cms/service/GoogleOAuthService.java
  src/main/java/com/handongapp/cms/service/TbuserService.java
  src/main/java/com/handongapp/cms/service/impl/GoogleOAuthServiceImpl.java
  src/main/java/com/handongapp/cms/service/impl/TbuserServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/application.yaml
Labels: feat

#23 Feat/21 make domain
  src/main/java/com/handongapp/cms/domain/AuditingFields.java
  src/main/java/com/handongapp/cms/domain/TbCourse.java
  src/main/java/com/handongapp/cms/domain/TbProgramCourse.java
  src/main/java/com/handongapp/cms/domain/TbProgramParticipant.java
  src/main/java/com/handongapp/cms/domain/TbProgramProgress.java
  src/main/java/com/handongapp/cms/domain/TbSection.java
  src/main/java/com/handongapp/cms/domain/enums/ProgramProgressState.java
Labels: feat

#24 Feat/22 make domain
  src/main/java/com/handongapp/cms/domain/TbComment.java
  src/main/java/com/handongapp/cms/domain/TbCommentOfCategory.java
  src/main/java/com/handongapp/cms/domain/TbCourseLastView.java
  src/main/java/com/handongapp/cms/domain/TbNode.java
  src/main/java/com/handongapp/cms/domain/TbNodeGroup.java
Labels: feat

#48 Fix/47/fix err
  src/main/java/com/handongapp/cms/CmsApplication.java
  src/main/java/com/handongapp/cms/auth/controller/GoogleLoginController.java
  src/main/java/com/handongapp/cms/auth/service/impl/GoogleOAuthServiceImpl.java
  src/main/java/com/handongapp/cms/config/MybatisConfig.java
  src/main/java/com/handongapp/cms/controller/v1/ClubController.java
  src/main/java/com/handongapp/cms/controller/v1/UserController.java
  src/main/java/com/handongapp/cms/dto/NodeDto.java
  src/main/java/com/handongapp/cms/dto/v1/CategoryOfCommentDto.java
  src/main/java/com/handongapp/cms/dto/v1/ClubDto.java
  src/main/java/com/handongapp/cms/dto/v1/NodeDto.java
  src/main/java/com/handongapp/cms/dto/v1/NodeGroupDto.java
  src/main/java/com/handongapp/cms/dto/v1/SectionDto.java
  src/main/java/com/handongapp/cms/dto/v1/UserDto.java
  src/main/java/com/handongapp/cms/mapper/ClubMapper.java
  src/main/java/com/handongapp/cms/mapper/TbUserMapper.java
  src/main/java/com/handongapp/cms/repository/ClubRepository.java
  src/main/java/com/handongapp/cms/repository/ClubRoleRepository.java
  src/main/java/com/handongapp/cms/repository/CommentOfCategoryRepository.java
  src/main/java/com/handongapp/cms/repository/CommentRepository.java
  src/main/java/com/handongapp/cms/repository/CourseLastViewRepository.java
  src/main/java/com/handongapp/cms/repository/CourseRepository.java
  src/main/java/com/handongapp/cms/repository/CourseRepositoryCustom.java
  src/main/java/com/handongapp/cms/repository/Custom/CourseRepositoryCustom.java
  src/main/java/com/handongapp/cms/repository/NodeGroupRepository.java
  src/main/java/com/handongapp/cms/repository/NodeRepository.java
  src/main/java/com/handongapp/cms/repository/ProgramCourseRepository.java
  src/main/java/com/handongapp/cms/repository/ProgramParticipantRepository.java
  src/main/java/com/handongapp/cms/repository/ProgramProgressRepository.java
  src/main/java/com/handongapp/cms/repository/ProgramRepository.java
  src/main/java/com/handongapp/cms/repository/SectionRepository.java
  src/main/java/com/handongapp/cms/repository/TbCourseRepository.java
  src/main/java/com/handongapp/cms/repository/UserClubRoleRepository.java
  src/main/java/com/handongapp/cms/repository/UserRepository.java
  src/main/java/com/handongapp/cms/repository/impl/CourseRepositoryImpl.java
  src/main/java/com/handongapp/cms/security/PrincipalDetailsService.java
  src/main/java/com/handongapp/cms/service/ClubService.java
  src/main/java/com/handongapp/cms/service/CourseService.java
  src/main/java/com/handongapp/cms/service/TbUserService.java
  src/main/java/com/handongapp/cms/service/UserService.java
  src/main/java/com/handongapp/cms/service/impl/ClubServiceImpl.java
  src/main/java/com/handongapp/cms/service/impl/CourseServiceImpl.java
  src/main/java/com/handongapp/cms/service/impl/NodeServiceImpl.java
  src/main/java/com/handongapp/cms/service/impl/UserServiceImpl.java
  src/main/resources/mapper/ClubMapper.xml
  src/main/resources/mapper/UserMapper.xml
Labels: bug

#59 프로그램 및 동아리 페이지 전체 마진값 수정
  .github/workflows/auto-reviewer.yml
  src/main/front/src/components/course/CourseLeaderboard.tsx
  src/main/front/src/pages/ClubPage.tsx
  src/main/front/src/pages/ProgramPage.tsx
Labels: fe

#64 Issue 및 PR 가이드 추가
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/docs_request.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/other.md
  .github/pull_request_template.md
Labels: documentation

#90 Feat/89/add login time
  src/main/resources/application.yaml
Labels: be
